service: simple-task-service
provider:
  name: aws
  region: us-west-2
  runtime: dotnetcore2.0
package:
  artifact: bin/release/netcoreapp2.0/say-hello-deploy.zip
  
functions:
  greet-by-name:
    handler: SayHelloService::SayHelloService.SayHello::GreetByName
    events:
      - http:
          path: greet/{name}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                name: true
  get-date:
    handler: SayHelloService::SayHelloService.SayHello::GetCurrentDateUtc
	events:
	  - http:
          path: get-date-utc
          method: GET
          cors: true
          authorizer:
            

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: say-hello-user-pool

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: say-hello-client
        UserPoolId:
          Ref: CognitoUserPool