service: simple-task-service
provider:
  name: aws
  region: us-west-2
  runtime: dotnetcore2.1
package:
  artifact: bin/release/netcoreapp2.1/say-hello-deploy.zip
  
functions:
  greet-by-name:
    handler: SayHelloService::SayHelloService.SayHello::GreetByName
    events:
      - http:
          path: greetings/{name}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                name: true
  utc-date:
    handler: SayHelloService::SayHelloService.SayHello::GetCurrentDateUtc
    events:
      - http:
          path: get-utc
          method: GET
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:451515956712:userpool/us-west-2_j8i0laMuA
            identitySource: method.request.header.Authorization

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: say-hello-user-pool

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: say-hello-client
        UserPoolId:
          Ref: CognitoUserPool
