service: simple-task-service
provider:
  name: aws
  region: us-west-2
  runtime: dotnetcore2.0
package:
  artifact: bin/release/netcoreapp2.0/say-hello-deploy.zip
  
functions:
  greet-by-name:
    handler: SayHelloService::SayHelloService.SayHello::GreetByName
    events:
      - http:
          path: greet/{name}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                name: true